apiVersion: webapp.colinbruner.com/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: controller-demo
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
